spring:
  application:
    name: figurinhas
  datasource:
    url: jdbc:h2:mem:figurinhasdb
    driverClassName: org.h2.Driver
    usuarioname: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

server:
  port: 8090
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# actuator
management:
  endpoint:
    health:
      show-details: always
    web:
      exposure:
        include:*