@host_usuarios = http://localhost:8100
@host_albuns = http://localhost:8080
@host_figurinhas = http://localhost:8090
@albumPrototipo_id = {{albumPrototipo.response.body.$.id}}
@figurinhaPrototipo1_id = {{figurinhaPrototipo1.response.body.$.id}}
@figurinhaPrototipo2_id = {{figurinhaPrototipo2.response.body.$.id}}
@figurinhaPrototipo3_id = {{figurinhaPrototipo3.response.body.$.id}}
@figurinhaPrototipo4_id = {{figurinhaPrototipo4.response.body.$.id}}
@figurinhaPrototipo5_id = {{figurinhaPrototipo5.response.body.$.id}}
@figurinhaPrototipo6_id = {{figurinhaPrototipo6.response.body.$.id}}
@figurinhaPrototipo7_id = {{figurinhaPrototipo7.response.body.$.id}}
@figurinhaPrototipo8_id = {{figurinhaPrototipo8.response.body.$.id}}
@figurinhaPrototipo9_id = {{figurinhaPrototipo9.response.body.$.id}}
@figurinhaPrototipo10_id = {{figurinhaPrototipo10.response.body.$.id}}
@figurinhaPrototipo11_id = {{figurinhaPrototipo11.response.body.$.id}}
@figurinhaPrototipo12_id = {{figurinhaPrototipo12.response.body.$.id}}
@figurinhaPrototipo13_id = {{figurinhaPrototipo13.response.body.$.id}}
@figurinhaPrototipo14_id = {{figurinhaPrototipo14.response.body.$.id}}
@figurinhaPrototipo15_id = {{figurinhaPrototipo15.response.body.$.id}}
@figurinhaPrototipo16_id = {{figurinhaPrototipo16.response.body.$.id}}
@figurinhaPrototipo17_id = {{figurinhaPrototipo17.response.body.$.id}}
@figurinhaPrototipo18_id = {{figurinhaPrototipo18.response.body.$.id}}
@figurinhaPrototipo19_id = {{figurinhaPrototipo19.response.body.$.id}}
@figurinhaPrototipo20_id = {{figurinhaPrototipo20.response.body.$.id}}
@usuario_id = {{Usuario.response.body.$.id}}
@usuarioDestination_id = {{usuarioDestination.response.body.$.id}}
@album_id = {{album.response.body.$.id}}
@albumDestination_id = {{albumDestination.response.body.$.id}}
@figurinha_id = {{figurinha.response.body.$.id}}


###
###
###
### Create Usuario
# @name Usuario

POST {{host_usuarios}}/usuarios HTTP/1.1

{
  "name":"usuario",
  "document":"1234",
  "email":"usuario@email",
  "address":{
    "street":"1",
    "number":"2",
    "neighborhood":"3",
    "complement":"4",
    "city":"sao paulo",
    "state":"sp",
    "zipCode":"1234"
  }
}

### Create usuarioDestination
# @name usuarioDestination

POST {{host_usuarios}}/usuarios HTTP/1.1

{
  "name":"usuario2",
  "document":"4321",
  "email":"usuario2@email",
  "address":{
    "street":"1",
    "number":"2",
    "neighborhood":"3",
    "complement":"4",
    "city":"sao paulo",
    "state":"sp",
    "zipCode":"1234"
  }
}

### Find All Usuarios

GET {{host_usuarios}}/usuarios HTTP/1.1


###
###
###
### Create Album Prototipo
# @name albumPrototipo

POST {{host_albuns}}/album/prototipo HTTP/1.1

{
  "name": "Fifa World Cup Qatar 2022",
  "cover": "imagem",
  "numFigurinhas": 20,
  "price": 50,
  "launchDate": "01-01-2022 00:00",
  "expirationDate": "31-12-2022 00:00"
}

### Find All

GET {{host_albuns}}/album/prototipo HTTP/1.1


###
###
###
### Create Figurinha Prototipo
# @name figurinhaPrototipo1

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
  "number": 1,
  "description": "Figurinha da Seleção",
  "image": "image",
  "rarity": 2,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo2

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
  "number": 2,
  "description": "Figurinha do Escudo do Brasil",
  "image": "image",
  "rarity": 2,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo3

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
  "number": 3,
  "description": "Figurinha do Goleiro Alisson",
  "image": "image",
  "rarity": 3,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo4

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 4,
    "description": "Figurinha do Goleiro Ederson",
    "image": "image",
    "rarity": 4,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo5

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 5,
    "description": "Figurinha do Alex Sandro",
    "image": "image",
    "rarity": 3,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo6

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 6,
    "description": "Figurinha do Danilo",
    "image": "image",
    "rarity": 3,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo7

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 7,
    "description": "Figurinha do Éder Militão",
    "image": "image",
    "rarity": 3,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo8

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 8,
    "description": "Figurinha do Marquinhos",
    "image": "image",
    "rarity": 3,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo9

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 9,
    "description": "Figurinha do Thiago Silva",
    "image": "image",
    "rarity": 2,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo10

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 10,
    "description": "Figurinha do Casemiro",
    "image": "image",
    "rarity": 2,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo11

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 11,
    "description": "Figurinha do Philippe Coutinho",
    "image": "image",
    "rarity": 4,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo12

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 12,
    "description": "Figurinha do Fabinho",
    "image": "image",
    "rarity": 4,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo13

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 13,
    "description": "Figurinha do Fred",
    "image": "image",
    "rarity": 4,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo14

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 14,
    "description": "Figurinha do Lucas Paquetá",
    "image": "image",
    "rarity": 4,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo15

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 15,
    "description": "Figurinha do Antony",
    "image": "image",
    "rarity": 4,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo16

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 16,
    "description": "Figurinha do Gabriel Jesus",
    "image": "image",
    "rarity": 3,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo17

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 17,
    "description": "Figurinha do Neymar Jr",
    "image": "image",
    "rarity": 1,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo18

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 18,
    "description": "Figurinha do Raphinha",
    "image": "image",
    "rarity": 4,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo19

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 19,
    "description": "Figurinha do Richarlison",
    "image": "image",
    "rarity": 4,
  "figurinhaPrice":100.00
}
###
# @name figurinhaPrototipo20

POST {{host_figurinhas}}/figurinha/prototipo HTTP/1.1

{
  "albumPrototipoId":"{{albumPrototipo_id}}",
    "number": 20,
    "description": "Figurinha do Vinícius Jr",
    "image": "image",
    "rarity": 1,
  "figurinhaPrice":100.00
}

### Find All

GET {{host_figurinhas}}/figurinha/prototipo HTTP/1.1


###
###
###
### Create Album
# @name album

POST {{host_albuns}}/album HTTP/1.1

{
  "usuarioId":"{{usuario_id}}",
  "albumPrototipoId":"{{albumPrototipo_id}}"
}


###
###
###
### Create Album
# @name albumDestination

POST {{host_albuns}}/album HTTP/1.1

{
  "usuarioId":"{{usuarioDestination_id}}}",
  "albumPrototipoId":"{{albumPrototipo_id}}"
}

### Find All Albuns

GET {{host_albuns}}/album HTTP/1.1


###
###
###
### Create Figurinha
# @name figurinha

POST {{host_figurinhas}}/figurinha HTTP/1.1

{
  "figurinhaPrototipoId":"{{figurinhaPrototipo1_id}}",
  "albumId":"{{album_id}}"
}


### Find All Figurinhas

GET {{host_figurinhas}}/figurinha HTTP/1.1


###
###
### 
### Put Up For Sale

POST {{host_figurinhas}}/figurinha/sell

{
    "figurinha": {
        "id": "{{figurinha_id}}"
    },
    "price": 3.97
}


###
###
### 
### Find All Figurinha For Sale

GET {{host_figurinhas}}/figurinha/sell


###
###
### 
### Buy Figurinha

POST {{host_figurinhas}}/figurinha/buy

{
    "figurinhaId": "{{figurinha_id}}",
    "destinationAlbumId": "{{albumDestination_id}}"
}


###
###
### 
### Buy Figurinha Pack <<<<<<<<<<<not working>>>>>>>>>>>

POST {{host_figurinhas}}/figurinha/buy/pack

{
    "albumId": "{{album_id}}",
    "destinationAlbumId": "{{albumDestination_id}}"
}


###
###
### 
### Album Journal

GET {{host_albuns}}/album/journal


###
###
### 
### Figurinha Journal

GET {{host_figurinhas}}/figurinha/journal